


spring:
  cloud:
    gateway:
      routes:
        - id: teacher-service
          uri: lb://TEACHER-SERVICE
          predicates:
            - Path=/teacher-assign/**
          filters:
            - AuthFilter

        - id: teacher-service
          uri: lb://TEACHER-SERVICE
          predicates:
            - Path=/teacher/**
          filters:
            - AuthFilter

        - id: courses-service
          uri: lb://courses-service
          predicates:
            - Path=/courses/**
        - id: subject-service
          uri: lb://subject-service
          predicates:
            - Path=/subject/**

        - id: securityApp
          uri: lb://SECURITYAPP
          predicates:
            - Path=/auth/**
          filters:
            - AuthFilter
