version: '3'
services:
  ### Posgres database for Teacher
  db-teacher:
    container_name: db-teacher
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_teacher
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Test123
    ports:
      - 5431:5431
    expose:
      - 5431
    command: -p 5431

  ### MySQL database for Course
  db-course:
    container_name: db-course
    image: mysql:8.0.33
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ms_course
      MYSQL_USER: admin
      MYSQL_PASSWORD: Test123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    expose:
      - 3306

  ### Posgres database for Subject
  db-subject:
    container_name: db-subject
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_subject
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Test123
    ports:
      - 5435:5432
    expose:
      - 5432
    command: -p 5432


##Adimin and security
  db-user:
    container_name: db-admin-user
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: securityDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Test123
    ports:
      - 5450:5450  # Cambiar al puerto 5450 en lugar de 5440
    expose:
      - 5450
    command: -p 5450

  ### Adminer for database management
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 9090:9090

  ### pgAdmin for PostgreSQL database management
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - 5051:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.0.2
    command: [ "start-dev" ]
    ports:
      - 8181:8181
    expose:
      - 8181
    depends_on:
      - db-keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db-keycloak
      DB_DATABASE: db_keycloak
      DB_PORT: 5433
      DB_USER: manueldev
      DB_PASSWORD: Test123
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8181

  db-keycloak:
    container_name: db-keycloak
    image: postgres:latest
    environment:
      POSTGRES_DB: db_keycloak
      POSTGRES_USER: manueldev
      POSTGRES_PASSWORD: Test123
    ports:
      - 5434:5432  # Changed external port to 5434
    volumes:
      - db-keycloak-data:/var/lib/postgresql/data

volumes:
  db-keycloak-data:
