version: '3'
services:
  ### Posgres database for Teacher
  ### Posgres database for Teacher
  db-teacher:
    container_name: db-teacher
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_teacher
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Test123
    ports:
      - 5431:5432

  ### MySQL database for Course
  db-course:
    container_name: db-course
    image: mysql:8.0.33
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ms_course
      MYSQL_USER: admin
      MYSQL_PASSWORD: Test123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306

  ### Posgres database for Subject
  db-subject:
    container_name: db-subject
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_subject
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Test123
    ports:
      - 5435:5432

  ##Admin and security
  db-user:
    container_name: db-admin-user
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: securityDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Test123
    ports:
      - 5450:5432

  db-student:
    image: mysql:8.0
    container_name: student_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ms_student
      MYSQL_USER: admin
      MYSQL_PASSWORD: Test123
    ports:
      - 3308:3306

  ### Adminer for database management
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 9090:9090

  ### pgAdmin for PostgreSQL database management
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - 5051:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin